# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_auto_20170412_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
